# ----------------------------------------------------------------------------
#
# Package             : dockerize
# Source Repo         : https://github.com/jwilder/dockerize
# Travis Job Link     : https://travis-ci.com/github/asellappen/dockerize/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: go

    
go_import_path: 
  - github.com/hpcloud/tail
  - github.com/jwilder/gojq

arch:
   - amd64
   - ppc64le
go:

  - "1.15.x"
  - "1.14.x"


sudo: false


install: true

script:

 - go build -v ./...
 - go test -v ./...
